# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
import os
class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(313, 301)
        dialog.setStyleSheet("background-color: #fff;")
        #dialog.setWindowIcon(QIcon(os.getcwd()+'\\title.jpg'))
        dialog.setWindowTitle("bitrogen")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 241, 81))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 221, 81))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 241, 81))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        dialog.setFixedSize(dialog.size())

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "bitrogen"))
        self.label_2.setText(_translate("dialog", " <a href=\"https://github.com/bitrogen\"> <font face=verdana size=24 color=black> Github</font> </a>"))
        self.label_3.setText(_translate("dialog", " <a href=\"https://www.youtube.com/channel/UCDx-KTToe7EB1OcTbmN_-8g\"> <font face=verdana size=12 color=red> Youtube</font> </a>"))
        self.label_4.setText(_translate("dialog", " <a href=\"https://bitrogen.github.io\"> <font face=verdana size=24 color=aqua> bitrogen</font> </a>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
