# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 596)
        #MainWindow.setWindowIcon("image.jfif")
        MainWindow.setStyleSheet(open("style.css", "r").read())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.questionLabel = QtWidgets.QLabel(self.centralwidget)
        self.questionLabel.setGeometry(QtCore.QRect(60, 40, 641, 191))
        self.questionLabel.setStyleSheet("")
        self.questionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.questionLabel.setObjectName("questionLabel")
        self.answer1 = QtWidgets.QPushButton(self.centralwidget)
        self.answer1.setGeometry(QtCore.QRect(60, 260, 311, 71))
        self.answer1.setObjectName("answer1")
        self.answer2 = QtWidgets.QPushButton(self.centralwidget)
        self.answer2.setGeometry(QtCore.QRect(420, 260, 281, 71))
        self.answer2.setObjectName("answer2")
        self.answer3 = QtWidgets.QPushButton(self.centralwidget)
        self.answer3.setGeometry(QtCore.QRect(60, 350, 311, 71))
        self.answer3.setObjectName("answer3")
        self.answer4 = QtWidgets.QPushButton(self.centralwidget)
        self.answer4.setGeometry(QtCore.QRect(420, 350, 281, 71))
        self.answer4.setObjectName("answer4")
        self.timeBar = QtWidgets.QLCDNumber(self.centralwidget)
        self.timeBar.setGeometry(QtCore.QRect(420, 440, 281, 81))
        self.timeBar.setObjectName("timeBar")
        self.scoreBar = QtWidgets.QLCDNumber(self.centralwidget)
        self.scoreBar.setGeometry(QtCore.QRect(60, 440, 311, 81))
        self.scoreBar.setObjectName("scoreBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionbitrogen = QtWidgets.QAction(MainWindow)
        self.actionbitrogen.setObjectName("actionbitrogen")
        self.menuFile.addAction(self.actionOpen)
        self.menuAbout.addAction(self.actionbitrogen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.questionLabel.setText(_translate("MainWindow", "TextLabel"))
        self.answer1.setText(_translate("MainWindow", "PushButton"))
        self.answer2.setText(_translate("MainWindow", "PushButton"))
        self.answer3.setText(_translate("MainWindow", "PushButton"))
        self.answer4.setText(_translate("MainWindow", "PushButton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionbitrogen.setText(_translate("MainWindow", "bitrogen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
